version: '3.9'

services:

  mongo_db:
    image: mongo:latest
    restart: always
    ports: 
      - 27017:27017
    volumes: 
      - mongodb:/data/db
    networks:
      - my_network

  backend:
    build: ./backend
    ports:
      - 5000:5000
    environment:
      MONGODB_URI: mongodb://mongo_db:27017
    depends_on:
      - mongo_db
    networks:
      - my_network

  frontend:
    build: ./client
    ports:
      - 3000:3000
    networks:
      - my_network
  
volumes:
  mongodb:

networks:
  my_network:
    driver: bridge